export const SET_PLACES = "SET_PLACES";
export const REMOVE_PLACE = "REMOVE_PLACE";
export const PLACE_ADDED = "PLACE_ADDED";
export const START_ADD_PLACE = "START_ADD_PLACE";

export const TRY_AUTH = "TRY_AUTH";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";

export const NIGHT_MODE_TOGGLE ="NIGHT_MODE_TOGGLE";

export const SET_PICKED_IMAGE ="SET_PICKED_IMAGE";
export const CLEAR_PICKED_IMAGE ="CLEAR_PICKED_IMAGE";
